In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
b= np.array([[1,2,3,4],[4,5,6,7]])

In [5]:
a
a.ndim
a.shape

(4,)

In [8]:
b@a # symbol for dot prod :internally np.dot


array([30, 60])

# TENSORS

In [18]:
np.arange(1,13).reshape(3,4,1)
# 24 == 24

# OR
np.array([[[1],[2],[3],[4]],[[5],[6],[7],[8]],[[9],[1],[2],[3]]])

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]],

       [[9],
        [1],
        [2],
        [3]]])

FUNCTIONS

In [29]:
#ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
#ones dtype
x = np.ones((2,3))
y =np.ones((2,3),dtype=np.int16)  # up casting
x+y


array([[2., 2., 2.],
       [2., 2., 2.]])

In [37]:
#arrange
np.arange(1,15).reshape(2,-1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
#flatteing an array
np.ravel(np.arange(1,15).reshape(2,-1)
)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
#transpose
x = np.transpose(np.arange(1,13).reshape(3,4))
# np.arange(1,13).reshape(3,4).T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [60]:
# a= np.arange(1,13).reshape(2,6)
# b=np.arange(1,13).reshape(2,6)


In [44]:
for k in np.nditer(x ):
  print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [55]:
a = np.arange(1,13).reshape(3,4)
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
a.sum(axis=0)

array([15, 18, 21, 24])

array([10, 26, 42])

In [58]:
a.prod(axis=0)

array([ 45, 120, 231, 384])

In [59]:
x = np.arange(1,401).reshape(100,4)
w = [1,2,3,4]
y = x @ w
y

array([  30,   70,  110,  150,  190,  230,  270,  310,  350,  390,  430,
        470,  510,  550,  590,  630,  670,  710,  750,  790,  830,  870,
        910,  950,  990, 1030, 1070, 1110, 1150, 1190, 1230, 1270, 1310,
       1350, 1390, 1430, 1470, 1510, 1550, 1590, 1630, 1670, 1710, 1750,
       1790, 1830, 1870, 1910, 1950, 1990, 2030, 2070, 2110, 2150, 2190,
       2230, 2270, 2310, 2350, 2390, 2430, 2470, 2510, 2550, 2590, 2630,
       2670, 2710, 2750, 2790, 2830, 2870, 2910, 2950, 2990, 3030, 3070,
       3110, 3150, 3190, 3230, 3270, 3310, 3350, 3390, 3430, 3470, 3510,
       3550, 3590, 3630, 3670, 3710, 3750, 3790, 3830, 3870, 3910, 3950,
       3990])

# SLICING

In [71]:
x = np.arange(1,13).reshape(3,4)
x[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
b = np.arange(20).reshape(5,4)
print(b)
b[2:4  , :]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
b[::-1]
# b[-1::]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [75]:
x[2][3]
masking = x==2
x[masking]

array([2])

In [82]:
np.where(masking  ,1,0 )

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# STACKING   AND SPLITTING

In [96]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

np.hstack((h1,h2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
np.vstack((h1,h2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# BROAD CASTING

In [120]:
one_d = np.array([1,2,3,4,5])
two_d = np.arange(1,21).reshape(4,5)
scaler =  10
print(two_d.shape)
print(one_d.shape)
t1 = one_d+scaler
t2 =  two_d + t1


(4, 5)
(5,)


In [121]:
t2

array([[12, 14, 16, 18, 20],
       [17, 19, 21, 23, 25],
       [22, 24, 26, 28, 30],
       [27, 29, 31, 33, 35]])

In [133]:
import time

AttributeError: module 'time' has no attribute 'now'

# TASK

In [155]:
t1 = time.time()
x  = np.random.randint(1,100 ,10000000 )
y1 = 3*(x**2) + 2*x + 1
t1 = time.time() - t1

In [156]:
y1

array([ 7601, 23942, 17481, ...,  4409,  8534, 14422])

In [147]:
t2 = time.time()
import random
x = [random.random() for _ in range(10000000)]
y = 3*(x**2) + 2*x + 1
t2 = time.time() - t2

In [151]:
import random
# x = [random.random() for _ in range(10000000)]
t2 = time.time()
l=[]
for _ in range(10000000):
  l.append(random.random())

t3 = time.time() - t2

In [153]:
l1 , l2 =[],[]
for i in l :
  temp = i*


In [148]:
t1

0.041831016540527344

In [149]:
t2

1.3638224601745605

# TASK 2

In [165]:
t1 = time.time()
x  = np.random.randint(1,100 ,10000000 ).reshape(2,-1)
y  = np.random.randint(1,100 ,10000000 ).reshape(2,-1)
print(x)
z = ((y[0]-x[0])**2 + (y[1]-x[1])**2)**0.5




[[19 11 52 ... 86 52 87]
 [85 13 16 ... 66 62 78]]
